### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by callmeYe** [CCI-Tools/demo#1]

**Comment by callmeYe** [comment]
CONFIG =
{'DATA_ROOT': 'E:\\'}
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\Scripts\ccitbxws-script.py", line 11, in <module>
    load_entry_point('ccitbxws', 'console_scripts', 'ccitbxws')()
  File "e:\viewer-demo-master\backend\ccitbxws\main.py", line 511, in main
    api = falcon.API(after=[crossdomain])
TypeError: __init__() got an unexpected keyword argument 'after'
